name = "DocumenterTypst"
uuid = "d7fd56dd-41bc-4b2d-b658-79a5840b2e09"
version = "0.1.0"
authors = ["Gabriel Wu <13583761+lucifer1004@users.noreply.github.com> and contributors"]

[deps]
ANSIColoredPrinters = "a4c015fc-c6ff-483c-b24f-f7ea428134e9"
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
MarkdownAST = "d0879d2d-cac2-40c8-9cee-1863dc0c7391"
Typst_jll = "eb4b1da6-20f6-5c66-9826-fdb8ad410d0e"

[compat]
ANSIColoredPrinters = "0"
Documenter = "1"
Markdown = "1"
MarkdownAST = "0.1"
Typst_jll = "0.14"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
